remote_theme: pmarsceill/just-the-docs
title: Theme pack support
description: Theme pack support for Sailfish OS
baseurl: "/"
permalink: pretty
exclude: ["harbour-themepacksupport/", "LICENSE", "*.png", "*.spec"]

search_enabled: true
aux_links:
    "Theme pack support on GitHub":
      - "//github.com/fravaccaro/themepacksupport-sailfishos"
