remote_theme: pmarsceill/just-the-docs
title: Theme pack support
description: Theme pack support for Sailfish OS
baseurl: ""
exclude: ["harbour-themepacksupport/", "LICENSE", "*.png", "*.spec"]

url: "https://uithemer.github.io/themepacksupport-sailfishos"
search_enabled: true
aux_links:
    "Theme pack support on GitHub":
      - "//github.com/uithemer/themepacksupport-sailfishos"
