remote_theme: pmarsceill/just-the-docs
title: Theme pack support
description: Theme pack support for Sailfish OS
permalink: pretty
exclude: ["harbour-themepacksupport/", "LICENSE", "*.png", "*.spec"]

search_enabled: true
